services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "0.0.0.0:7860:8080"
    volumes:
      - open-webui:/app/backend/data
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always

  cloudflare_ollama: # Cloudflared Token for "ollama_server" Tunnel
    image: cloudflare/cloudflared:latest
    network_mode: host # これのおかげで localhost を参照できるが、悪さもしている？
    container_name: cloudflared_ollama
    restart: always
    command: tunnel --no-autoupdate --url http://localhost:11434 # network_mode: host を使うと localhost が参照できる
    # command: tunnel --no-autoupdate --url http://ollama:11434
    # depends_on:
    #   - ollama
    # command: tunnel --no-autoupdate run --url http://localhost:11434 --token eyJhIjoiOTExY2RhN2Y1ZTE4ODBhMTgwZGM1YmMzZDM3MWQyMWIiLCJ0IjoiMzBkOTRkNmYtYWFkZS00YWI2LTkzMWMtOWQ4ZmIxNTAyNDI3IiwicyI6Ill6Sm1ZMk0xTkRrdFl6Z3hZeTAwTW1NMUxUZzJPR0V0WWpZd01EaGlNekZoWVRRMCJ9

  cloudflare_webui:
    image: docker.io/cloudflare/cloudflared:latest
    network_mode: host
    container_name: cloudflared_webui
    restart: always
    command: tunnel --no-autoupdate --url http://localhost:7860
    # command: tunnel --no-autoupdate run --url http://localhost:7860 --token eyJhIjoiOTExY2RhN2Y1ZTE4ODBhMTgwZGM1YmMzZDM3MWQyMWIiLCJ0IjoiMzBkOTRkNmYtYWFkZS00YWI2LTkzMWMtOWQ4ZmIxNTAyNDI3IiwicyI6Ill6Sm1ZMk0xTkRrdFl6Z3hZeTAwTW1NMUxUZzJPR0V0WWpZd01EaGlNekZoWVRRMCJ9

  cloudflare_dify:
    image: docker.io/cloudflare/cloudflared:latest
    network_mode: host
    container_name: cloudflared_dify
    restart: always
    command: tunnel --no-autoupdate --url http://localhost:80
    # command: tunnel --no-autoupdate run --url http://localhost:7860 --token eyJhIjoiOTExY2RhN2Y1ZTE4ODBhMTgwZGM1YmMzZDM3MWQyMWIiLCJ0IjoiMzBkOTRkNmYtYWFkZS00YWI2LTkzMWMtOWQ4ZmIxNTAyNDI3IiwicyI6Ill6Sm1ZMk0xTkRrdFl6Z3hZeTAwTW1NMUxUZzJPR0V0WWpZd01EaGlNekZoWVRRMCJ9


volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui
