services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "0.0.0.0:7860:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # environment:
    #   - OLLAMA_BASE_URL=http://ollama:11434
    # depends_on:
    #   - ollama
    restart: always

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui
